### Test page
GET  http://localhost:3333/v1/

### Test 404
GET  http://localhost:3333/v1/qldyur


### ----------
### AUTHORS 
### ------------
### Get all authors
GET  http://localhost:3333/v1/authors

### Get one author
GET http://localhost:3333/v1/authors/2

### Add new author (json style)
POST http://localhost:3333/v1/authors/save
Content-Type: application/json

{
    "first_name": "Steph",
    "last_name": "Andria",
    "birth_date": "1991-08-12",
    "birth_place": "Lille (FR)"
}

### Add new author (urlencoded style)
POST http://localhost:3333/v1/authors/save
Content-Type: application/x-www-form-urlencoded

first_name=Stepĥ
&last_name=Steph
&birth_date=1991-04-03
&birth_place=Paris (FR)

### Update an author
PATCH http://localhost:3333/v1/authors/update
Content-Type: application/x-www-form-urlencoded

id=10
&first_name=Jamie
&last_name=Andria
&birth_date=1991-08-12
&birth_place=Lille (FR)

### Delete an author
DELETE http://localhost:3333/v1/authors/2

### Get books by author
GET http://localhost:3333/v1/authors/1/books


### ------------
### BOOKS 
### ------------
### Add new book (urlencoded style)
POST http://localhost:3333/v1/books/save
Content-Type: application/x-www-form-urlencoded

title=booktitle
&cover_image=test
&summary=lots of text
&serie_id=1

### Update a book
PATCH http://localhost:3333/v1/books/update
Content-Type: application/x-www-form-urlencoded

id=12
&title=newTitle
&cover_image=image
&summary=theSummary
&serie_id=2

### Delete a book
DELETE http://localhost:3333/v1/books/11


### ----------
### SERIES 
### ------------
### Get all series
GET  http://localhost:3333/v1/series

### Get one serie
GET http://localhost:3333/v1/series/11

### Add new serie (urlencoded style)
POST http://localhost:3333/v1/series/save
Content-Type: application/x-www-form-urlencoded

label=New label

### Update an serie
PATCH http://localhost:3333/v1/series/update
Content-Type: application/x-www-form-urlencoded

id=11
&label=ffff

### Delete a serie
DELETE http://localhost:3333/v1/series/13

### Get books by serie
GET http://localhost:3333/v1/series/1/books