### ----------
### USER 
### ------------
### Get all user
GET  http://localhost:3333/v1/user

### Get one user
GET http://localhost:3333/v1/user/2

### Add new user (json style)
POST http://localhost:3333/v1/user/signup
Content-Type: application/json

{
    "userName": "Jamie",
    "email": "jamie@andria.com",
    "password": "password"
}

### Log in
POST http://localhost:3333/v1/user/login
Content-Type: application/json

{
    "userName": "Steph",
    "password": "password"
}

### Delete an user
DELETE http://localhost:3333/v1/user/4

